# PENS数据集配置

# 数据路径
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  embeddings: "data/embeddings"
  results: "results/baseline"

# 数据预处理配置
preprocessing:
  # 分词配置
  tokenization:
    tokenizer: "basic"  # basic, spacy, bert
    lowercase: true
    remove_punctuation: false
    
  # 序列长度配置
  sequence_lengths:
    max_title_length: 30
    max_body_length: 500
    max_sentence_length: 50
    max_user_history: 50
  
  # 词汇表配置
  vocabulary:
    vocab_size: 50000
    min_word_freq: 2
    special_tokens:
      - "<PAD>"
      - "<UNK>"
      - "<SOS>"
      - "<EOS>"
      - "<COPY>"
  
  # 数据分割配置
  data_split:
    train_ratio: 0.8
    valid_ratio: 0.1
    test_ratio: 0.1
    random_seed: 42

  # 数据采样配置（使用采样数据以节省存储空间）
  data_sample_ratio: 0.1  # 使用10%的原始数据
  max_samples_per_split: null  # 移除样本数量限制
  max_pos_samples_per_user: 3  # 减少每个用户的正样本数
  max_neg_samples_per_user: 2  # 减少每个用户的负样本数
  negative_sample_ratio: 0.05  # 减少负样本采样比例到5%
  
  # 文本长度限制
  max_body_length: 500  # 恢复完整的body长度
  max_user_history: 50   # 恢复完整的用户历史长度

  # 分块处理配置（降低内存占用）
  chunk_size: 5000  # 每块处理5000条记录
  save_frequency: 3  # 每处理3块保存一次中间结果

# 数据加载配置
data_loader:
  batch_size: 128  # 增大batch size以配合全量数据
  shuffle: true
  num_workers: 8  # 增加worker数量
  pin_memory: true
  drop_last: false

# 新闻类别配置
news_categories:
  - "entertainment"
  - "news"
  - "sports"
  - "finance"
  - "lifestyle"
  - "travel"
  - "foodanddrink"
  - "health"
  - "kids"
  - "movies"
  - "music"
  - "tv"
  - "video"
  - "weather"
  - "autos"